# Generated by Django 5.2.1 on 2025-06-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=2, unique=True),
            preserve_default=False,
        ),
    ]
